name = "PopGenSims"
uuid = "e670a858-c023-4621-870e-30d0f49b8322"
authors = ["Pavel Dimens <pdimens@live.com> and contributors"]
version = "0.0.2"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
InvertedIndices = "41ab1584-1d38-5bbf-9106-f11c6c58b48f"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
PopGen = "af524d12-c74b-11e9-22a8-3b091653023f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DataFrames = "0.21"
InvertedIndices = "1.0"
PooledArrays = "0.5"
PopGen = "0.0.3, 0.1"
StaticArrays = "0.12"
StatsBase = "0.33"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
